service: liquid-tabulator

provider:
  name: aws
  runtime: python3.6
  environment:
    GOOGLE_SHEET_KEY: ${env:LIQUID_TABULATOR_GSHEET_KEY}
    GOOGLE_SHEET_RANGE: ${env:LIQUID_TABULATOR_GSHEET_RANGE}

functions:
  tabulate:
    handler: handler.tabulate
    events:
      - http:
          path: /
          method: get
          private: false

package:
  exclude:
    - .git/**
    - node_modules/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    # dockerImage: <image name>:tag
    dockerizePip: true
    zip: true
    noDeploy:
      - docopt
